### ISSUE TITLE
repeat.item.number and repeat.item.index don't seem to work with recursion

### ISSUE THREAD

**Issue by marcidy** [malthe/chameleon#177]
When using a recursive structure such as below, the repeat.item.number and index don't appear to behave in a sane way.  I'm not sure why they decrement once, then stay the same for the current level.  They do seem to reset on recursion, but the behavior of next and subsequent values isn't what I would expect.

``` html
  <body>
    <div class="step_list" metal:define-macro="thing_list">
      <div class="step" tal:repeat="item thing">
        Repeat Index: <span tal:content="repeat.item.index">test</span>
        Repeat Number: <span tal:content="repeat.item.number">test</span>
        <div tal:define="thing item.children">
          <div metal:use-macro="template.macros['thing_list']" />
        </div>
      </div>
    </div>
  </body>
```

![repeat_numbers](https://cloud.githubusercontent.com/assets/5845312/3580016/bbbb852c-0bcc-11e4-93c7-0f4d0606bd66.png)

**Comment by pgrunewald** [comment]
I'm experiencing the very same issue. I have posted on example here: https://community.plone.org/t/weird-behavior-in-tal-chameleon-with-nested-repeats-and-macros/453

One issue seems to be, that any previous state of the `repeat` variable does not get restored, after having finished a tal:repeat block/scope.

@marcidy I'm curious, what's your work-around for this?

**Comment by malthe** [comment]
My work around for this issue – pending being fixed – is to use:

      tal:define="(i, item) enumerate(sequence)"

This gives you an explicit iterator index as a scoped variable.

But I think it's a nasty bug that should be fixed. I took a brief look and it's not clear how to best go about it because the repeat dictionary is very simple and not "scoped".

**Comment by marcidy** [comment]
I never posted my work-around (or actual solution?), sorry about that.

``` XML
1<div class="step_list" metal:define-macro="step_list" >
2  <div tal:repeat="step steps">
3 < all other stuff  />
4 <div tal:define="steps step.children">
5   <div metal:use-macro="template.macros['step_list']" />
6 </div>
```

Forgive the abuse of notation below.  "Step0" and "Step1" are both variables with the label "step".
```
1 define macro
2 start loop with steps = "steps0"
3 hit macro and set steps = step0.steps a.k.a "steps1"
4 run inside macro which exhausts steps aka "step1.steps"
5 exit macro and go back to line 2 and get next step from "steps0"
```

line 2 is a potential issue with this, the label "steps" is reassigned but the original list of steps still exists to be iterated after the macro exists.  Not sure if this is a problem or a feature.  Feature to me right now : )


Hope this can help in some way.  Let me know if there's anything else I can do.  Again, apologies for not posting this before, especially to @pgrunewald

**Comment by dataflake** [comment]
This appears to be a matter of local scopes not being cleaned up when the local scope is left. Consider this simplistic example with a list of lists. The `tal:condition` is used to stop processing at the inner list:

```
<div tal:define="seq python:[[1, 2, 3]]*4">
    <div metal:define-macro="nested_repeat">
      <div tal:condition="python: same_type(seq, [])"
           tal:repeat="item seq">
        Repeat Index: <span tal:content="repeat/item/index">test</span>
        Repeat Number: <span tal:content="repeat/item/number">test</span>
        <div tal:define="seq item">
          <div metal:use-macro="template/macros/nested_repeat" />
        </div>
      </div>
    </div>
</div>
```

The result:

```
Repeat Index: 0 Repeat Number: 1
Repeat Index: 0 Repeat Number: 1
Repeat Index: 1 Repeat Number: 2
Repeat Index: 2 Repeat Number: 3
Repeat Index: 2 Repeat Number: 3
Repeat Index: 0 Repeat Number: 1
Repeat Index: 1 Repeat Number: 2
Repeat Index: 2 Repeat Number: 3
Repeat Index: 2 Repeat Number: 3
Repeat Index: 0 Repeat Number: 1
Repeat Index: 1 Repeat Number: 2
Repeat Index: 2 Repeat Number: 3
Repeat Index: 2 Repeat Number: 3
Repeat Index: 0 Repeat Number: 1
Repeat Index: 1 Repeat Number: 2
Repeat Index: 2 Repeat Number: 3
```

The example shows that the inner repeat loop initializes the `repeat` variables correctly, but when the inner loop ends and the outer loop runs again those local values are not cleaned up correctly. The outer loop now shows the last `repeat` variable values that were set on the inner loop.
